Repository RedstoneTools/redstonetools-mod, pull requests merged in 2023-06, with the labels that each got.

#228 Fixed //read default blockstate
  src/main/java/tools/redstone/redstonetools/features/commands/BinaryBlockReadFeature.java
Labels: general/high-priority, pr/needs-testing

#221 AirPlace with Leftclick
  src/main/java/tools/redstone/redstonetools/mixin/features/AirplaceMixin.java
Labels: pr/needs-testing

#244 /glass -> /colored
  src/main/java/tools/redstone/redstonetools/features/arguments/ColoredBlockTypeSerializer.java
  src/main/java/tools/redstone/redstonetools/features/commands/ColoredFeature.java
  src/main/java/tools/redstone/redstonetools/features/commands/GlassFeature.java
  src/main/java/tools/redstone/redstonetools/utils/ColoredBlockType.java
Labels: general/high-priority, pr/needs-testing

#235 Macro Command Max Length Fix
  src/main/java/tools/redstone/redstonetools/macros/gui/widget/commandlist/CommandEntry.java
Labels: pr/needs-testing

#218 Duplicate Macro Bind Indicator
  src/main/java/tools/redstone/redstonetools/macros/KeyBindingMixin.java
  src/main/java/tools/redstone/redstonetools/macros/Macro.java
  src/main/java/tools/redstone/redstonetools/macros/gui/screen/MacroEditScreen.java
  src/main/java/tools/redstone/redstonetools/mixin/macros/KeyBindingMixinImpl.java
  src/main/java/tools/redstone/redstonetools/utils/KeyBindingUtils.java
Labels: pr/needs-testing

#251 DO_CONTAINER_DROPS only affects containers
  src/main/java/tools/redstone/redstonetools/mixin/gamerules/DoContainerDropsMixin.java
Labels: pr/needs-testing

#240 /itembind and compatibility fix
  src/main/java/tools/redstone/redstonetools/RedstoneToolsClient.java
  src/main/java/tools/redstone/redstonetools/features/commands/CopyStateFeature.java
  src/main/java/tools/redstone/redstonetools/features/commands/ItemBindFeature.java
  src/main/java/tools/redstone/redstonetools/macros/WorldlessCommandHelper.java
  src/main/java/tools/redstone/redstonetools/macros/gui/MaroCommandSuggestor.java
  src/main/java/tools/redstone/redstonetools/macros/gui/commandsuggestor/WorldlessCommandSource.java
  src/main/java/tools/redstone/redstonetools/macros/gui/screen/CommandEditScreen.java
  src/main/java/tools/redstone/redstonetools/macros/gui/widget/commandlist/CommandEntry.java
  src/main/java/tools/redstone/redstonetools/mixin/features/ItemBindMixin.java
  src/main/java/tools/redstone/redstonetools/mixin/macros/autocomplete/CommandDispatcherMixin.java
  src/main/java/tools/redstone/redstonetools/mixin/macros/autocomplete/CommandSuggestorMixin.java
  src/main/java/tools/redstone/redstonetools/utils/ItemUtils.java
  src/main/resources/redstonetools.mixins.json
Labels: general/high-priority

#285 Removing Telemetry
  src/main/java/tools/redstone/redstonetools/mixin/telemetry/InitializeTelemetryClientMixin.java
  src/main/java/tools/redstone/redstonetools/mixin/telemetry/SendCommandMixin.java
  src/main/java/tools/redstone/redstonetools/mixin/telemetry/SendCrashReportMixin.java
  src/main/java/tools/redstone/redstonetools/mixin/telemetry/ShowTelemetryPopupMixin.java
  src/main/java/tools/redstone/redstonetools/telemetry/TelemetryClient.java
  src/main/java/tools/redstone/redstonetools/telemetry/TelemetryManager.java
  src/main/java/tools/redstone/redstonetools/telemetry/dto/TelemetryAuth.java
  src/main/java/tools/redstone/redstonetools/telemetry/dto/TelemetryCommand.java
  src/main/java/tools/redstone/redstonetools/telemetry/dto/TelemetryException.java
  src/main/java/tools/redstone/redstonetools/utils/TelemetryUtils.java
  src/main/resources/redstonetools.mixins.json
Labels: pr/needs-testing
